# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170612_1230'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
