# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170612_1238'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postlike',
            table='post_post_like_users',
        ),
    ]
