# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.2 on 2017-06-20 05:59
=======
# Generated by Django 1.11.2 on 2017-06-20 05:52
>>>>>>> e5278c3fc0369ff8fa911dace01b1d0a28cb1c8d
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('post', '0003_auto_20170619_1239'),
=======
        ('post', '0003_auto_20170619_0338'),
>>>>>>> e5278c3fc0369ff8fa911dace01b1d0a28cb1c8d
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
