# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.2 on 2017-06-20 06:01
=======
# Generated by Django 1.11.2 on 2017-06-20 05:53
>>>>>>> e5278c3fc0369ff8fa911dace01b1d0a28cb1c8d
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(to='post.Tag'),
        ),
    ]
